# Generated by Django 5.2.4 on 2025-08-03 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domaine')),
                ('url', models.URLField(verbose_name="URL d'origine")),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('key_points', models.JSONField(default=dict, verbose_name='Points clés')),
                ('what_you_accept', models.TextField(blank=True, verbose_name='Ce que vous acceptez')),
                ('data_collected', models.TextField(blank=True, verbose_name='Données collectées')),
                ('data_usage', models.TextField(blank=True, verbose_name='Utilisation des données')),
                ('data_sharing', models.TextField(blank=True, verbose_name='Partage des données')),
                ('retention_period', models.TextField(blank=True, verbose_name='Durée de conservation')),
                ('critical_points', models.TextField(blank=True, verbose_name='Points critiques')),
                ('readability_score', models.IntegerField(default=0, verbose_name='Score de lisibilité (1-10)')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé')], default='moderate', max_length=10, verbose_name='Niveau de risque')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('documents_found', models.JSONField(default=list, verbose_name='Documents trouvés')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Analyse réussie')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Analyse de site web',
                'verbose_name_plural': 'Analyses de sites web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', "Conditions d'utilisation"), ('privacy', 'Politique de confidentialité'), ('cookies', 'Politique de cookies'), ('legal', 'Mentions légales'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('url', models.URLField(verbose_name='URL du document')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'extraction")),
                ('content_length', models.IntegerField(default=0, verbose_name='Longueur du contenu')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='analyzer.websiteanalysis', verbose_name='Analyse')),
            ],
            options={
                'verbose_name': 'Document juridique',
                'verbose_name_plural': 'Documents juridiques',
                'unique_together': {('analysis', 'url')},
            },
        ),
    ]
